// @generated by tools/convert_planarian_glb_surface.py; do not edit by hand.
use rusty_matter_mesh::TriangleMeshSurface;
use rusty_matter_model::Vec3;

pub(crate) const PLANARIA_SKETCHFAB_SURFACE_ID: &str =
    "mesh.planarian_ap.sketchfab_educational_surface";
pub(crate) const PLANARIA_SKETCHFAB_SOURCE_URL: &str =
    "https://sketchfab.com/3d-models/planaria-8e5a7c4e312e4b08b20676608cb2399f";
pub(crate) const PLANARIA_SKETCHFAB_LICENSE: &str = "CC-BY-4.0";
pub(crate) const PLANARIA_SKETCHFAB_ATTRIBUTION: &str = "aphanizomenon, Planaria, Sketchfab";
pub(crate) const PLANARIA_SKETCHFAB_EVIDENCE_TYPE: &str = "educational_abstraction";
pub(crate) const PLANARIA_SKETCHFAB_SOURCE_SHA256: &str =
    "a170a62ba705a81e73dd7fcfb5808431ff1a0b5c0da6322742c1e2c6ce480dda";
pub(crate) const PLANARIA_SKETCHFAB_SOURCE_SIZE_BYTES: usize = 741032;
pub(crate) const PLANARIA_SKETCHFAB_VERTEX_COUNT: usize = 13663;
pub(crate) const PLANARIA_SKETCHFAB_TRIANGLE_COUNT: usize = 23468;
pub(crate) const PLANARIA_SKETCHFAB_TOPOLOGY_INDEX_HASH: u64 = 17537816352375156885;
pub(crate) const PLANARIA_SKETCHFAB_GENERATOR: &str = "convert_planarian_glb_surface.py";
pub(crate) const PLANARIA_SKETCHFAB_GLTF_GENERATOR: &str = "Sketchfab-12.68.0";
pub(crate) const PLANARIA_SKETCHFAB_AXIS_MAPPING: &str = "z";
pub(crate) const PLANARIA_SKETCHFAB_TARGET_LENGTH: f32 = 1.65;
pub(crate) const PLANARIA_SKETCHFAB_SCALE: f32 = 0.490960687;
pub(crate) const PLANARIA_SKETCHFAB_CENTER_AFTER_SCALE: [f32; 3] = [0.0, -0.391232102, -0.39041584];
pub(crate) const PLANARIA_SKETCHFAB_Y_OFFSET: f32 = -0.09;
pub(crate) const PLANARIA_SKETCHFAB_SOURCE_BOUNDS_MIN: [f32; 3] =
    [-0.933754981, -1.94913805, -2.47558689];
pub(crate) const PLANARIA_SKETCHFAB_SOURCE_BOUNDS_MAX: [f32; 3] =
    [0.933754981, 0.355396986, 0.885170996];
pub(crate) const PLANARIA_SKETCHFAB_BOUNDS_MIN: [f32; 3] = [-0.458436986, -0.655718051, -0.825];
pub(crate) const PLANARIA_SKETCHFAB_BOUNDS_MAX: [f32; 3] = [0.458436986, 0.475718051, 0.825];
pub(crate) const PLANARIA_SKETCHFAB_SOURCE_VERTEX_COUNT: usize = 13663;

const PLANARIA_SKETCHFAB_SURFACE_BYTES: &[u8] =
    include_bytes!("planarian_mesh_asset/planaria_sketchfab_surface.bin");
const PLANARIA_SKETCHFAB_POSITION_BYTES: usize = PLANARIA_SKETCHFAB_VERTEX_COUNT * 3 * 4;
const PLANARIA_SKETCHFAB_TRIANGLE_BYTES: usize = PLANARIA_SKETCHFAB_TRIANGLE_COUNT * 3 * 4;
const PLANARIA_SKETCHFAB_SURFACE_BYTES_LEN: usize =
    PLANARIA_SKETCHFAB_POSITION_BYTES + PLANARIA_SKETCHFAB_TRIANGLE_BYTES;

pub(crate) fn sketchfab_planaria_surface() -> TriangleMeshSurface {
    assert_eq!(
        PLANARIA_SKETCHFAB_SURFACE_BYTES.len(),
        PLANARIA_SKETCHFAB_SURFACE_BYTES_LEN,
        "generated Planaria surface binary length must match declared counts",
    );

    let positions = PLANARIA_SKETCHFAB_SURFACE_BYTES[..PLANARIA_SKETCHFAB_POSITION_BYTES]
        .chunks_exact(12)
        .map(|chunk| Vec3::new(read_f32(chunk, 0), read_f32(chunk, 4), read_f32(chunk, 8)))
        .collect();
    let triangles = PLANARIA_SKETCHFAB_SURFACE_BYTES[PLANARIA_SKETCHFAB_POSITION_BYTES..]
        .chunks_exact(12)
        .map(|chunk| [read_u32(chunk, 0), read_u32(chunk, 4), read_u32(chunk, 8)])
        .collect();

    TriangleMeshSurface::new(PLANARIA_SKETCHFAB_SURFACE_ID, positions, triangles)
}

fn read_f32(chunk: &[u8], offset: usize) -> f32 {
    let mut bytes = [0_u8; 4];
    bytes.copy_from_slice(&chunk[offset..offset + 4]);
    f32::from_le_bytes(bytes)
}

fn read_u32(chunk: &[u8], offset: usize) -> u32 {
    let mut bytes = [0_u8; 4];
    bytes.copy_from_slice(&chunk[offset..offset + 4]);
    u32::from_le_bytes(bytes)
}
