[package]
name = "rusty-matter-particles"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = []
parallel = ["rusty-matter-batch/rayon"]
serde = ["dep:serde", "rusty-matter-model/serde", "rusty-matter-sdf/serde"]

[dependencies]
rusty-matter-batch = { path = "../rusty-matter-batch" }
rusty-matter-mesh = { path = "../rusty-matter-mesh" }
rusty-matter-model = { path = "../rusty-matter-model" }
rusty-matter-sdf = { path = "../rusty-matter-sdf" }
serde = { version = "1", features = ["derive"], optional = true }

[lints]
workspace = true
