[package]
name = "rusty-matter-batch"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = []
rayon = ["dep:rayon"]

[dependencies]
rayon = { version = "1", optional = true }

[lints]
workspace = true
